server:
  port: 8989
spring:
  application:
    name: service-miya
  cloud:
    client:
      ipAddress: 127.0.0.1
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
