server:
  port: 8769
spring:
  application:
    name: service-zuul
  cloud:
    client:
      ipAddress: 127.0.0.1

eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
  instance:
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}

## 服务路由
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign

