server:
  port: 9761

eureka:
  instance:
    prefer-ip-address: true
    hostname: peer2
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://peer1:8761/eureka/

spring:
  application:
    name: eurka-server
  profiles:
    active: peer2

