server:
  port: 8763 # 8762 8763
spring:
  application:
    name: service-hi
  cloud:
    client:
      ipAddress: 127.0.0.1
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://peer1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
