server:
  port: 8764
spring:
  application:
    name: service-ribbon
  cloud:
    client:
      ipAddress: 127.0.0.1

eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
  instance:
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
