server:
  port: 10000
spring:
  application:
    name: service-turbine
  cloud:
    client:
      ipAddress: 127.0.0.1
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://peer1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

## 这一块配置必须加上,否则 http://localhost:10000/actuator/hystrix.stream 连不上
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
turbine:
  app-config: service-hi,service-miya
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  combine-host-port: true
  instanceUrlSuffix:
      default: actuator/hystrix.stream
